In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a=np.array([1,2,3,7])

In [7]:
a

array([1, 2, 3, 7])

In [8]:
a[3]=30

In [9]:
a

array([ 1,  2,  3, 30])

In [10]:
np.arrange(10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##multidimensional arrays

In [13]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
a=np.array([[1,2,3],
          [4,5,6],
         [7,8,9]
         ])

In [17]:
a[0,1]=40

In [18]:
a

array([[ 1, 40,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

## Randomly Generated Array

In [22]:
np.random.seed(10)
np.random.rand(3,3)

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084]])

In [23]:
np.random.seed(2)
np.random.randint(low=1,high=10,size=(3,4))

array([[9, 9, 7, 3],
       [9, 8, 3, 2],
       [6, 5, 5, 6]], dtype=int32)

# Element-Wise operation

In [26]:
a=np.arange(5)

In [32]:
b=(10+(a*2))**2/100

In [33]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [34]:
a+b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Complrison Operation

In [36]:
a

array([0, 1, 2, 3, 4])

In [37]:
a>=2

array([False, False,  True,  True,  True])

In [39]:
a>b

array([False, False,  True,  True,  True])

## Summerizing operation

In [40]:
a

array([0, 1, 2, 3, 4])

In [41]:
a.max()

np.int64(4)

In [42]:
a.sum()

np.int64(10)